DROP TABLE IF EXISTS goals CASCADE;

CREATE TABLE goals (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id uuid REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  amount INTEGER NOT NULL
);